version: '3.8'
services:
  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      microservices-network:

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      microservices-network:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    networks:
      microservices-network:

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8081:8081"
    depends_on:
       - eureka-server
    networks:
      microservices-network:

  cart-service:
    build: ./cart-service
    container_name: cart-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
    networks:
      microservices-network:

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    networks:
      microservices-network:

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
    networks:
      microservices-network:

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"

networks:
  microservices-network:
    driver: bridge