server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - JwtAuthenticationFilter

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - JwtAuthenticationFilter

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/auth/**



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
