server:
  port: 8084
spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:mysql://localhost:3306/cart
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      hibernate:
          ddl-auto: update
      show-sql: true

eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka